// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ka2iZDuLZRczy7yQTcifgT
// Component: L8i0x8iks7JL

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CmsQueryRepeater } from "@plasmicpkgs/plasmic-cms";
import ComponentsInstructorInstructor from "../../ComponentsInstructorInstructor"; // plasmic-import: UrXh7aqakI5i/component

import {
  ThemeValue,
  useTheme
} from "../17_sds_foundation_global/PlasmicGlobalVariant__Theme"; // plasmic-import: yBTVTgAz2Co9/globalVariant
import { useScreenVariants as useScreenVariantsohEUf6Jd0EV8 } from "../17_sds_foundation_global/PlasmicGlobalVariant__Screen"; // plasmic-import: OhEUf6Jd0eV8/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_17_sds_foundation_global_css from "../17_sds_foundation_global/plasmic.module.css"; // plasmic-import: 3BHMWCYAenCmWb8ThbnzeF/projectcss
import plasmic_17_sds_foundation_system_css from "../17_sds_foundation_system/plasmic.module.css"; // plasmic-import: dNqcW7FYVqnkjtbdVGjyS8/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: ka2iZDuLZRczy7yQTcifgT/projectcss
import sty from "./PlasmicComponentsAuthorAuthors.module.css"; // plasmic-import: L8i0x8iks7JL/css

createPlasmicElementProxy;

export type PlasmicComponentsAuthorAuthors__VariantMembers = {
  usage: "lineUp";
};
export type PlasmicComponentsAuthorAuthors__VariantsArgs = {
  usage?: SingleChoiceArg<"lineUp">;
};
type VariantPropType = keyof PlasmicComponentsAuthorAuthors__VariantsArgs;
export const PlasmicComponentsAuthorAuthors__VariantProps =
  new Array<VariantPropType>("usage");

export type PlasmicComponentsAuthorAuthors__ArgsType = {
  authorName?: string;
};
type ArgPropType = keyof PlasmicComponentsAuthorAuthors__ArgsType;
export const PlasmicComponentsAuthorAuthors__ArgProps = new Array<ArgPropType>(
  "authorName"
);

export type PlasmicComponentsAuthorAuthors__OverridesType = {
  root?: Flex__<"div">;
  cmsDataFetcher?: Flex__<typeof CmsQueryRepeater>;
  componentsInstructorInstructor?: Flex__<
    typeof ComponentsInstructorInstructor
  >;
};

export interface DefaultComponentsAuthorAuthorsProps {
  authorName?: string;
  usage?: SingleChoiceArg<"lineUp">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicComponentsAuthorAuthors__RenderFunc(props: {
  variants: PlasmicComponentsAuthorAuthors__VariantsArgs;
  args: PlasmicComponentsAuthorAuthors__ArgsType;
  overrides: PlasmicComponentsAuthorAuthors__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "usage",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.usage
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    theme: useTheme(),
    screen: useScreenVariantsohEUf6Jd0EV8()
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_17_sds_foundation_global_css.plasmic_tokens,
        plasmic_17_sds_foundation_system_css.plasmic_tokens,
        sty.root,
        {
          [plasmic_17_sds_foundation_global_css.global_theme_darkGrayscale]:
            hasVariant(globalVariants, "theme", "darkGrayscale"),
          [plasmic_17_sds_foundation_global_css.global_theme_dark]: hasVariant(
            globalVariants,
            "theme",
            "dark"
          ),
          [plasmic_17_sds_foundation_global_css.global_theme_grayscale]:
            hasVariant(globalVariants, "theme", "grayscale"),
          [sty.rootusage_lineUp]: hasVariant($state, "usage", "lineUp")
        }
      )}
    >
      <CmsQueryRepeater
        data-plasmic-name={"cmsDataFetcher"}
        data-plasmic-override={overrides.cmsDataFetcher}
        className={classNames("__wab_instance", sty.cmsDataFetcher)}
        desc={false}
        emptyMessage={
          <DataCtxReader__>
            {$ctx => (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___1HiVc
                )}
              >
                {"No matching published entries found."}
              </div>
            )}
          </DataCtxReader__>
        }
        filterField={"name"}
        filterValue={args.authorName}
        forceEmptyState={false}
        forceLoadingState={false}
        limit={0}
        loadingMessage={
          <DataCtxReader__>
            {$ctx => (
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__zjkds
                )}
              >
                {"Loading..."}
              </div>
            )}
          </DataCtxReader__>
        }
        noAutoRepeat={false}
        noLayout={false}
        table={"author"}
        useDraft={false}
      >
        <DataCtxReader__>
          {$ctx => (
            <ComponentsInstructorInstructor
              data-plasmic-name={"componentsInstructorInstructor"}
              data-plasmic-override={overrides.componentsInstructorInstructor}
              className={classNames(
                "__wab_instance",
                sty.componentsInstructorInstructor,
                {
                  [sty.componentsInstructorInstructorusage_lineUp]: hasVariant(
                    $state,
                    "usage",
                    "lineUp"
                  )
                }
              )}
              entryField={"name"}
              imageField={(() => {
                try {
                  return $ctx.plasmicCmsAuthorItem.data.pic;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return undefined;
                  }
                  throw e;
                }
              })()}
              usage={"lineUp"}
            />
          )}
        </DataCtxReader__>
      </CmsQueryRepeater>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "cmsDataFetcher", "componentsInstructorInstructor"],
  cmsDataFetcher: ["cmsDataFetcher", "componentsInstructorInstructor"],
  componentsInstructorInstructor: ["componentsInstructorInstructor"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  cmsDataFetcher: typeof CmsQueryRepeater;
  componentsInstructorInstructor: typeof ComponentsInstructorInstructor;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicComponentsAuthorAuthors__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicComponentsAuthorAuthors__VariantsArgs;
    args?: PlasmicComponentsAuthorAuthors__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicComponentsAuthorAuthors__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicComponentsAuthorAuthors__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicComponentsAuthorAuthors__ArgProps,
          internalVariantPropNames: PlasmicComponentsAuthorAuthors__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicComponentsAuthorAuthors__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicComponentsAuthorAuthors";
  } else {
    func.displayName = `PlasmicComponentsAuthorAuthors.${nodeName}`;
  }
  return func;
}

export const PlasmicComponentsAuthorAuthors = Object.assign(
  // Top-level PlasmicComponentsAuthorAuthors renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    cmsDataFetcher: makeNodeComponent("cmsDataFetcher"),
    componentsInstructorInstructor: makeNodeComponent(
      "componentsInstructorInstructor"
    ),

    // Metadata about props expected for PlasmicComponentsAuthorAuthors
    internalVariantProps: PlasmicComponentsAuthorAuthors__VariantProps,
    internalArgProps: PlasmicComponentsAuthorAuthors__ArgProps
  }
);

export default PlasmicComponentsAuthorAuthors;
/* prettier-ignore-end */
